/*
 * generated by Xtext 2.23.0
 */
package co7217.dsl.ucd.web;

import co7217.dsl.ucd.UseCaseDSLRuntimeModule;
import co7217.dsl.ucd.UseCaseDSLStandaloneSetup;
import co7217.dsl.ucd.ide.UseCaseDSLIdeModule;
import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages in web applications.
 */
public class UseCaseDSLWebSetup extends UseCaseDSLStandaloneSetup {
	
	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new UseCaseDSLRuntimeModule(), new UseCaseDSLIdeModule(), new UseCaseDSLWebModule()));
	}
	
}
