/*
 * generated by Xtext 2.23.0
 */
package co7217.dsl.ucd.web;

import org.eclipse.xtext.web.server.DefaultWebModule;

/**
 * Manual modifications go to {@link UseCaseDSLWebModule}.
 */
@SuppressWarnings("all")
public abstract class AbstractUseCaseDSLWebModule extends DefaultWebModule {

}
