/*
 * generated by Xtext 2.23.0
 */
package co7217.dsl.ucd.parser.antlr;

import co7217.dsl.ucd.parser.antlr.internal.InternalUseCaseDSLParser;
import co7217.dsl.ucd.services.UseCaseDSLGrammarAccess;
import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class UseCaseDSLParser extends AbstractAntlrParser {

	@Inject
	private UseCaseDSLGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalUseCaseDSLParser createParser(XtextTokenStream stream) {
		return new InternalUseCaseDSLParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Diagram";
	}

	public UseCaseDSLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(UseCaseDSLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
