/*
 * generated by Xtext 2.23.0
 */
package co7217.dsl.ucd.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractUseCaseDSLScopeProvider extends DelegatingScopeProvider {
}
