/*
 * generated by Xtext 2.23.0
 */
package co7217.dsl.ucd;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class UseCaseDSLStandaloneSetup extends UseCaseDSLStandaloneSetupGenerated {

	public static void doSetup() {
		new UseCaseDSLStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
