/*
 * generated by Xtext 2.23.0
 */
package co7217.dsl.ucd.ide;


/**
 * Use this class to register ide components.
 */
public class UseCaseDSLIdeModule extends AbstractUseCaseDSLIdeModule {
}
