/**
 * generated by Xtext 2.23.0
 */
package co7217.dsl.ucd.useCaseDSL;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Actor</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link co7217.dsl.ucd.useCaseDSL.Actor#getName <em>Name</em>}</li>
 *   <li>{@link co7217.dsl.ucd.useCaseDSL.Actor#getType <em>Type</em>}</li>
 *   <li>{@link co7217.dsl.ucd.useCaseDSL.Actor#getUsecase <em>Usecase</em>}</li>
 * </ul>
 *
 * @see co7217.dsl.ucd.useCaseDSL.UseCaseDSLPackage#getActor()
 * @model
 * @generated
 */
public interface Actor extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see co7217.dsl.ucd.useCaseDSL.UseCaseDSLPackage#getActor_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link co7217.dsl.ucd.useCaseDSL.Actor#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Type</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' reference.
   * @see #setType(Actor)
   * @see co7217.dsl.ucd.useCaseDSL.UseCaseDSLPackage#getActor_Type()
   * @model
   * @generated
   */
  Actor getType();

  /**
   * Sets the value of the '{@link co7217.dsl.ucd.useCaseDSL.Actor#getType <em>Type</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' reference.
   * @see #getType()
   * @generated
   */
  void setType(Actor value);

  /**
   * Returns the value of the '<em><b>Usecase</b></em>' reference list.
   * The list contents are of type {@link co7217.dsl.ucd.useCaseDSL.Usecase}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Usecase</em>' reference list.
   * @see co7217.dsl.ucd.useCaseDSL.UseCaseDSLPackage#getActor_Usecase()
   * @model
   * @generated
   */
  EList<Usecase> getUsecase();

} // Actor
