/**
 * generated by Xtext 2.23.0
 */
package co7217.dsl.ucd.useCaseDSL;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see co7217.dsl.ucd.useCaseDSL.UseCaseDSLFactory
 * @model kind="package"
 * @generated
 */
public interface UseCaseDSLPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "useCaseDSL";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.dsl.co7217/ucd/UseCaseDSL";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "useCaseDSL";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  UseCaseDSLPackage eINSTANCE = co7217.dsl.ucd.useCaseDSL.impl.UseCaseDSLPackageImpl.init();

  /**
   * The meta object id for the '{@link co7217.dsl.ucd.useCaseDSL.impl.DiagramImpl <em>Diagram</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see co7217.dsl.ucd.useCaseDSL.impl.DiagramImpl
   * @see co7217.dsl.ucd.useCaseDSL.impl.UseCaseDSLPackageImpl#getDiagram()
   * @generated
   */
  int DIAGRAM = 0;

  /**
   * The feature id for the '<em><b>Elements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DIAGRAM__ELEMENTS = 0;

  /**
   * The number of structural features of the '<em>Diagram</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DIAGRAM_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link co7217.dsl.ucd.useCaseDSL.impl.AbstractElementImpl <em>Abstract Element</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see co7217.dsl.ucd.useCaseDSL.impl.AbstractElementImpl
   * @see co7217.dsl.ucd.useCaseDSL.impl.UseCaseDSLPackageImpl#getAbstractElement()
   * @generated
   */
  int ABSTRACT_ELEMENT = 1;

  /**
   * The number of structural features of the '<em>Abstract Element</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ABSTRACT_ELEMENT_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link co7217.dsl.ucd.useCaseDSL.impl.UseCasesImpl <em>Use Cases</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see co7217.dsl.ucd.useCaseDSL.impl.UseCasesImpl
   * @see co7217.dsl.ucd.useCaseDSL.impl.UseCaseDSLPackageImpl#getUseCases()
   * @generated
   */
  int USE_CASES = 2;

  /**
   * The feature id for the '<em><b>Use Case</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int USE_CASES__USE_CASE = ABSTRACT_ELEMENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Use Cases</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int USE_CASES_FEATURE_COUNT = ABSTRACT_ELEMENT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link co7217.dsl.ucd.useCaseDSL.impl.UsecaseImpl <em>Usecase</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see co7217.dsl.ucd.useCaseDSL.impl.UsecaseImpl
   * @see co7217.dsl.ucd.useCaseDSL.impl.UseCaseDSLPackageImpl#getUsecase()
   * @generated
   */
  int USECASE = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int USECASE__NAME = 0;

  /**
   * The feature id for the '<em><b>Instructions</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int USECASE__INSTRUCTIONS = 1;

  /**
   * The number of structural features of the '<em>Usecase</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int USECASE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link co7217.dsl.ucd.useCaseDSL.impl.ActorsImpl <em>Actors</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see co7217.dsl.ucd.useCaseDSL.impl.ActorsImpl
   * @see co7217.dsl.ucd.useCaseDSL.impl.UseCaseDSLPackageImpl#getActors()
   * @generated
   */
  int ACTORS = 4;

  /**
   * The feature id for the '<em><b>Actor</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTORS__ACTOR = ABSTRACT_ELEMENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Actors</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTORS_FEATURE_COUNT = ABSTRACT_ELEMENT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link co7217.dsl.ucd.useCaseDSL.impl.ActorImpl <em>Actor</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see co7217.dsl.ucd.useCaseDSL.impl.ActorImpl
   * @see co7217.dsl.ucd.useCaseDSL.impl.UseCaseDSLPackageImpl#getActor()
   * @generated
   */
  int ACTOR = 5;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTOR__NAME = 0;

  /**
   * The feature id for the '<em><b>Type</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTOR__TYPE = 1;

  /**
   * The feature id for the '<em><b>Usecase</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTOR__USECASE = 2;

  /**
   * The number of structural features of the '<em>Actor</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTOR_FEATURE_COUNT = 3;


  /**
   * Returns the meta object for class '{@link co7217.dsl.ucd.useCaseDSL.Diagram <em>Diagram</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Diagram</em>'.
   * @see co7217.dsl.ucd.useCaseDSL.Diagram
   * @generated
   */
  EClass getDiagram();

  /**
   * Returns the meta object for the containment reference list '{@link co7217.dsl.ucd.useCaseDSL.Diagram#getElements <em>Elements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Elements</em>'.
   * @see co7217.dsl.ucd.useCaseDSL.Diagram#getElements()
   * @see #getDiagram()
   * @generated
   */
  EReference getDiagram_Elements();

  /**
   * Returns the meta object for class '{@link co7217.dsl.ucd.useCaseDSL.AbstractElement <em>Abstract Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Abstract Element</em>'.
   * @see co7217.dsl.ucd.useCaseDSL.AbstractElement
   * @generated
   */
  EClass getAbstractElement();

  /**
   * Returns the meta object for class '{@link co7217.dsl.ucd.useCaseDSL.UseCases <em>Use Cases</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Use Cases</em>'.
   * @see co7217.dsl.ucd.useCaseDSL.UseCases
   * @generated
   */
  EClass getUseCases();

  /**
   * Returns the meta object for the containment reference list '{@link co7217.dsl.ucd.useCaseDSL.UseCases#getUseCase <em>Use Case</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Use Case</em>'.
   * @see co7217.dsl.ucd.useCaseDSL.UseCases#getUseCase()
   * @see #getUseCases()
   * @generated
   */
  EReference getUseCases_UseCase();

  /**
   * Returns the meta object for class '{@link co7217.dsl.ucd.useCaseDSL.Usecase <em>Usecase</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Usecase</em>'.
   * @see co7217.dsl.ucd.useCaseDSL.Usecase
   * @generated
   */
  EClass getUsecase();

  /**
   * Returns the meta object for the attribute '{@link co7217.dsl.ucd.useCaseDSL.Usecase#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see co7217.dsl.ucd.useCaseDSL.Usecase#getName()
   * @see #getUsecase()
   * @generated
   */
  EAttribute getUsecase_Name();

  /**
   * Returns the meta object for the attribute '{@link co7217.dsl.ucd.useCaseDSL.Usecase#getInstructions <em>Instructions</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Instructions</em>'.
   * @see co7217.dsl.ucd.useCaseDSL.Usecase#getInstructions()
   * @see #getUsecase()
   * @generated
   */
  EAttribute getUsecase_Instructions();

  /**
   * Returns the meta object for class '{@link co7217.dsl.ucd.useCaseDSL.Actors <em>Actors</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Actors</em>'.
   * @see co7217.dsl.ucd.useCaseDSL.Actors
   * @generated
   */
  EClass getActors();

  /**
   * Returns the meta object for the containment reference list '{@link co7217.dsl.ucd.useCaseDSL.Actors#getActor <em>Actor</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Actor</em>'.
   * @see co7217.dsl.ucd.useCaseDSL.Actors#getActor()
   * @see #getActors()
   * @generated
   */
  EReference getActors_Actor();

  /**
   * Returns the meta object for class '{@link co7217.dsl.ucd.useCaseDSL.Actor <em>Actor</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Actor</em>'.
   * @see co7217.dsl.ucd.useCaseDSL.Actor
   * @generated
   */
  EClass getActor();

  /**
   * Returns the meta object for the attribute '{@link co7217.dsl.ucd.useCaseDSL.Actor#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see co7217.dsl.ucd.useCaseDSL.Actor#getName()
   * @see #getActor()
   * @generated
   */
  EAttribute getActor_Name();

  /**
   * Returns the meta object for the reference '{@link co7217.dsl.ucd.useCaseDSL.Actor#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Type</em>'.
   * @see co7217.dsl.ucd.useCaseDSL.Actor#getType()
   * @see #getActor()
   * @generated
   */
  EReference getActor_Type();

  /**
   * Returns the meta object for the reference list '{@link co7217.dsl.ucd.useCaseDSL.Actor#getUsecase <em>Usecase</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Usecase</em>'.
   * @see co7217.dsl.ucd.useCaseDSL.Actor#getUsecase()
   * @see #getActor()
   * @generated
   */
  EReference getActor_Usecase();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  UseCaseDSLFactory getUseCaseDSLFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link co7217.dsl.ucd.useCaseDSL.impl.DiagramImpl <em>Diagram</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see co7217.dsl.ucd.useCaseDSL.impl.DiagramImpl
     * @see co7217.dsl.ucd.useCaseDSL.impl.UseCaseDSLPackageImpl#getDiagram()
     * @generated
     */
    EClass DIAGRAM = eINSTANCE.getDiagram();

    /**
     * The meta object literal for the '<em><b>Elements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DIAGRAM__ELEMENTS = eINSTANCE.getDiagram_Elements();

    /**
     * The meta object literal for the '{@link co7217.dsl.ucd.useCaseDSL.impl.AbstractElementImpl <em>Abstract Element</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see co7217.dsl.ucd.useCaseDSL.impl.AbstractElementImpl
     * @see co7217.dsl.ucd.useCaseDSL.impl.UseCaseDSLPackageImpl#getAbstractElement()
     * @generated
     */
    EClass ABSTRACT_ELEMENT = eINSTANCE.getAbstractElement();

    /**
     * The meta object literal for the '{@link co7217.dsl.ucd.useCaseDSL.impl.UseCasesImpl <em>Use Cases</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see co7217.dsl.ucd.useCaseDSL.impl.UseCasesImpl
     * @see co7217.dsl.ucd.useCaseDSL.impl.UseCaseDSLPackageImpl#getUseCases()
     * @generated
     */
    EClass USE_CASES = eINSTANCE.getUseCases();

    /**
     * The meta object literal for the '<em><b>Use Case</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference USE_CASES__USE_CASE = eINSTANCE.getUseCases_UseCase();

    /**
     * The meta object literal for the '{@link co7217.dsl.ucd.useCaseDSL.impl.UsecaseImpl <em>Usecase</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see co7217.dsl.ucd.useCaseDSL.impl.UsecaseImpl
     * @see co7217.dsl.ucd.useCaseDSL.impl.UseCaseDSLPackageImpl#getUsecase()
     * @generated
     */
    EClass USECASE = eINSTANCE.getUsecase();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute USECASE__NAME = eINSTANCE.getUsecase_Name();

    /**
     * The meta object literal for the '<em><b>Instructions</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute USECASE__INSTRUCTIONS = eINSTANCE.getUsecase_Instructions();

    /**
     * The meta object literal for the '{@link co7217.dsl.ucd.useCaseDSL.impl.ActorsImpl <em>Actors</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see co7217.dsl.ucd.useCaseDSL.impl.ActorsImpl
     * @see co7217.dsl.ucd.useCaseDSL.impl.UseCaseDSLPackageImpl#getActors()
     * @generated
     */
    EClass ACTORS = eINSTANCE.getActors();

    /**
     * The meta object literal for the '<em><b>Actor</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ACTORS__ACTOR = eINSTANCE.getActors_Actor();

    /**
     * The meta object literal for the '{@link co7217.dsl.ucd.useCaseDSL.impl.ActorImpl <em>Actor</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see co7217.dsl.ucd.useCaseDSL.impl.ActorImpl
     * @see co7217.dsl.ucd.useCaseDSL.impl.UseCaseDSLPackageImpl#getActor()
     * @generated
     */
    EClass ACTOR = eINSTANCE.getActor();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ACTOR__NAME = eINSTANCE.getActor_Name();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ACTOR__TYPE = eINSTANCE.getActor_Type();

    /**
     * The meta object literal for the '<em><b>Usecase</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ACTOR__USECASE = eINSTANCE.getActor_Usecase();

  }

} //UseCaseDSLPackage
