/**
 * generated by Xtext 2.23.0
 */
package co7217.dsl.ucd.useCaseDSL;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Use Cases</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link co7217.dsl.ucd.useCaseDSL.UseCases#getUseCase <em>Use Case</em>}</li>
 * </ul>
 *
 * @see co7217.dsl.ucd.useCaseDSL.UseCaseDSLPackage#getUseCases()
 * @model
 * @generated
 */
public interface UseCases extends AbstractElement
{
  /**
   * Returns the value of the '<em><b>Use Case</b></em>' containment reference list.
   * The list contents are of type {@link co7217.dsl.ucd.useCaseDSL.Usecase}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Use Case</em>' containment reference list.
   * @see co7217.dsl.ucd.useCaseDSL.UseCaseDSLPackage#getUseCases_UseCase()
   * @model containment="true"
   * @generated
   */
  EList<Usecase> getUseCase();

} // UseCases
